server:
  port: 8081

spring:

  h2:
    console:
      enabled: true
      path: /h2-console

  redis:
    host: localhost
    port: 6379

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/oauth
    username: qwer1234
    password: qwer1234
  #JPA ??
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    # Security OAuth
  security:
    oauth2.client:
      registration:
        google:
          clientId: 340165487474-f6rv04513gt94itd139vkap088fbk4h9.apps.googleusercontent.com
          clientSecret: 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
          redirect-uri: http://localhost:8081/login/oauth2/code/google
          scope:
            - email
            - profile
            -
  cors:
    allowed-origins: 'http://localhost:3001'
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: '*'
    max-age: 3600

  # jwt secret key
  jwt:
    secret: XNuPmL/do82G77OpWucoQl+WBXFBpAF6LoPNWj7/RJk=


  app:
    auth:
      tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
      tokenExpiry: 1800000
      refreshTokenExpiry: 604800000
    oauth2:
      authorizedRedirectUris:
        - http://localhost:3000/oauth/redirect
